### ISSUE TITLE
No LICENSE.md

### ISSUE THREAD

**Issue by bboyho** [sparkfun/Digital_Handpan#1]
Yo @JoelEB ,

I updated the README.md to link your project image and blog posts. I noticed that there was no LICENSE.md in this GitHub repo. I noticed that you added a beerware in the code but would you like an official license attached? ;D

**Comment by JoelEB** [comment]
Yes, please add a legit license, please and thanks Bobby!

**Comment by bboyho** [comment]
Done. =)
